language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install:
  - rm -f Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
sudo: false
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      bundler_args: --without system_tests development
      env: PUPPET_VERSION="~> 4.10" CHECK=test
    - rvm: 2.4.4
      bundler_args: --without system_tests development
      env: PUPPET_VERSION="~> 5.6" CHECK=test
    - rvm: 2.5.1
      bundler_args: --without system_tests development
      env: PUPPET_VERSION="~> 6.1" CHECK=rubocop
notifications:
  email:
    - adam.crews@gmail.com
  slack:
    secure: ZvqcIVgI4KmQgiQv6GzoKXG/imLSqaniSTcv4vHdlShO+vlMHma9rh9xK1lXU0aEFaWHn7c/58P2ucVWoK11N0H1/mzaK2YifljioxhNWNc1K4eOGR/xNwyOaHuvbbZJ8J0lw3s+G6MvTgCNXh92dS6nxiAw4rjY7P0hVy9qbSw=
